apiVersion: v1
kind: Secret
metadata:
  name: smartims-secrets
  namespace: smartims
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "root123"
  JWT_SECRET: "328ab64504a10d82e8932c611214908d373cada0d85727feb82c9b557818dbd1"
  GMAIL_USERNAME: "basavabm30@gmail.com"
  GMAIL_PASSWORD: "ydzw jphm qnxs vkoh"
